### PR TITLE
heb.json support hebrew

### PR DESCRIPTION
**Pull request by noamhasingit**
Adding Hebrew translations files

### CODE REVIEW

**Review by iternio — CHANGES_REQUESTED** [review]
That was fast! I suspect Google translate may have been involved here? There are some red-marked formatting errors if you view it on Github - these will typically fail our JSON reader. Could you have a look at those?

**Comment by noamhasingit** [comment]
> That was fast! I suspect Google translate may have been involved here? There are some red-marked formatting errors if you view it on Github - these will typically fail our JSON reader. Could you have a look at those?

Hi Man, I have submitted a commit with file fixes (sorry abt that).  Yes we decided to use google translate. it looks ok. but maybe in the future if users will complains will submit better text. for now it looks ok.

**Review by iternio — APPROVED** [review]
Ok, let's see how it works - we probably don't do RTL very well yet...

**Comment by noamhasingit** [comment]
When next release will be available?
Thank you

**Comment by iternio** [comment]
Unfortunately, 4.0.45 was just released (coming on iOS today, hopefully), but we will probably make some bug fix release next week. Web may be updated sooner as it is in our hands.

**Pull request merged**
