### PR TITLE
Update cs.json

### PR DESCRIPTION
**Pull request by jtfcobra**
add czech language text

### CODE REVIEW

**Review by iternio — COMMENTED** [review]
In the editor, you will see red markings when there is a JSON format error (which will prevent the file from working in ABRP) - please fix those first.

**Review by jtfcobra — COMMENTED** [review]
Please what error?

**Comment by jtfcobra** [comment]
Please what error thanks ?

**Comment by iternio** [comment]
> Please what error thanks ?

  "delete_share": "Delete share connection" lacks a comma (,) after which is a syntax error

**Comment by jtfcobra** [comment]
OK repaid Delete share connection

**Review by jtfcobra — COMMENTED** [review]
Ok

**Review by iternio — APPROVED** [review]

**Pull request merged**
