### PR TITLE
Minor language changes

### PR DESCRIPTION
**Pull request by PomkHU**

### CODE REVIEW

**Review by iternio — COMMENTED** [review]
Line 844 contains two strings on one line, and therefore the JSON parser will think the document is broken (I think, last version had the same problem).
Lines 861-868 are deleted, please leave them as English if you don't want to translate them now.

**Review by iternio — COMMENTED** [review]
This change conflicts with the version on master right now, and due to my bad Hungarian I cannot tell which is better :) 
Please merge and update the PR!

**Review by PomkHU — COMMENTED** [review]
Checked the latest version and this one is the better one. 
I'm looking for the option to merge it

**Review by iternio — APPROVED** [review]
I hope my manual merge worked as it should - and thanks!

**Pull request merged**
